name: Download MP3 & Convert to Opus Release
on:
  workflow_dispatch:

jobs:
  download_convert_release:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Install dependencies
      - name: Install ffmpeg & wget
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg wget

      # 3. Download MP3
      - name: Download MP3
        run: |
          wget --user-agent="Mozilla/5.0" \
          "https://theta.123tokyo.xyz/get.php/a/63/Y1xRFwLBpWw.mp3?n=Good%20mood%F0%9F%98%8EPositive%20songs%20to%20start%20your%20day%20-%20Tiktok%20Trending%20Songs%202023%20%232&uT=R&uN=RWxzYXZhZG9y&h=7v7IT6QE-VRwzwSUNZp7dw&s=1758388397&uT=R&uN=RWxzYXZhZG9y" \
          -O "Good_Mood_Song.mp3"

      # 4. Convert to WA-compatible Opus
      - name: Convert MP3 to Opus WA-compatible
        run: |
          ffmpeg -i "Good_Mood_Song.mp3" \
                 -c:a libopus \
                 -ar 16000 \
                 -ac 1 \
                 -b:a 32k \
                 -map_metadata 0 \
                 "Good_Mood_Song.opus"

      # 5. Create GitHub Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0
          release_name: MP3 & Opus Release v1.0.0
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      # 6. Upload MP3 & Opus
      - name: Upload MP3
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Good_Mood_Song.mp3
          asset_name: Good_Mood_Song.mp3
          asset_content_type: audio/mpeg

      - name: Upload Opus
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Good_Mood_Song.opus
          asset_name: Good_Mood_Song.opus
          asset_content_type: audio/opus
