name: YouTube Audio to Release
on:
  workflow_dispatch:

jobs:
  download_convert_release:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip ffmpeg
          python3 -m pip install --upgrade yt-dlp

      # 3. Download audio from YouTube
      - name: Download audio from YouTube
        run: |
          yt-dlp -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 \
          --output "Good_Mood_Song.%(ext)s" \
          "https://youtu.be/Y1xRFwLBpWw"

      # 4. Convert MP3 to WA-compatible Opus
      - name: Convert MP3 to Opus WA-compatible
        run: |
          ffmpeg -i "Good_Mood_Song.mp3" \
                 -c:a libopus \
                 -ar 16000 \
                 -ac 1 \
                 -b:a 32k \
                 -map_metadata 0 \
                 "Good_Mood_Song.opus"

      # 5. Create GitHub Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0
          release_name: YouTube Audio Release v1.0.0
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      # 6. Upload MP3
      - name: Upload MP3
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Good_Mood_Song.mp3
          asset_name: Good_Mood_Song.mp3
          asset_content_type: audio/mpeg

      # 7. Upload Opus
      - name: Upload Opus
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Good_Mood_Song.opus
          asset_name: Good_Mood_Song.opus
          asset_content_type: audio/opus
